name: minimalisticpush
description: A minimalistic push-up application.

publish_to: 'none' # do not remove

version: 1.5.1+35

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  shared_preferences:
  theme_provider:
  url_launcher:
  share:
  flutter_localizations:
    sdk: flutter
  path_provider:
  all_sensors:
  clipboard:
  sprinkle:

  cupertino_icons: ^0.1.3 # check if needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  effective_dart: ^1.3.0

flutter_icons:
  image_path: 'assets/icons/app_icon.png'
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png